// Code generated by MockGen. DO NOT EDIT.
// Source: internal/controller/patient/controller.go
//
// Generated by this command:
//
//	mockgen --source=internal/controller/patient/controller.go --destination=internal/mocks/mock_patient_controller.go --package=mocks --mock_names=service=MockPatientService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	query "github.com/nachoconques0/diagnosis_svc/internal/helpers/query"
	model "github.com/nachoconques0/diagnosis_svc/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockPatientService is a mock of service interface.
type MockPatientService struct {
	ctrl     *gomock.Controller
	recorder *MockPatientServiceMockRecorder
	isgomock struct{}
}

// MockPatientServiceMockRecorder is the mock recorder for MockPatientService.
type MockPatientServiceMockRecorder struct {
	mock *MockPatientService
}

// NewMockPatientService creates a new mock instance.
func NewMockPatientService(ctrl *gomock.Controller) *MockPatientService {
	mock := &MockPatientService{ctrl: ctrl}
	mock.recorder = &MockPatientServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPatientService) EXPECT() *MockPatientServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPatientService) Create(ctx context.Context, req model.CreatePatientRequest) (*model.PatientResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*model.PatientResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPatientServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPatientService)(nil).Create), ctx, req)
}

// Find mocks base method.
func (m *MockPatientService) Find(ctx context.Context, filters query.DiagnosisFilters, pagination query.Pagination) ([]model.PatientResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, filters, pagination)
	ret0, _ := ret[0].([]model.PatientResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockPatientServiceMockRecorder) Find(ctx, filters, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockPatientService)(nil).Find), ctx, filters, pagination)
}
